import { defineConfig, presetUno, transformerDirectives } from 'unocss'

export default defineConfig({
  presets: [presetUno()],
  transformers: [transformerDirectives()],
  theme: {
    colors: {
      // Zachování vašich brand barev
      primary: '#E60000',
      secondary: '#96B623',
      dark: '#000000',
      light: '#FFFFFF',
      'bg-light': '#E5E5E3',
      'gray-light': '#D0D0D0',
      'gray-dark': '#B0ADAC',
    },
  },
  shortcuts: {
    // Button utilities
    btn: 'relative inline-flex items-center justify-center font-semibold rounded-lg cursor-pointer transition-all duration-300 font-inherit whitespace-nowrap overflow-hidden outline-none border-2 border-transparent',
    'btn-primary': 'bg-primary text-white border-primary hover:bg-red-700 hover:border-red-700 hover:-translate-y-0.5 hover:shadow-lg hover:shadow-primary/20',
    'btn-secondary': 'bg-secondary text-white border-secondary hover:bg-green-700 hover:border-green-700 hover:-translate-y-0.5 hover:shadow-lg hover:shadow-secondary/20',
    'btn-outline': 'bg-transparent border-current hover:bg-black/5 hover:-translate-y-0.5',
    'btn-text': 'bg-transparent border-transparent px-2 hover:bg-black/5',
    'btn-danger': 'bg-red-600 text-white border-red-600 hover:bg-red-700 hover:border-red-700 hover:-translate-y-0.5 hover:shadow-lg hover:shadow-red-600/20',
    'btn-success': 'bg-green-600 text-white border-green-600 hover:bg-green-700 hover:border-green-700 hover:-translate-y-0.5 hover:shadow-lg hover:shadow-green-600/20',
    'btn-sm': 'px-3 py-1.5 text-sm rounded-md',
    'btn-md': 'px-5 py-2.5 text-base',
    'btn-lg': 'px-6 py-3 text-lg',
    'btn-block': 'flex w-full',
    'btn-rounded': 'rounded-full',
    'btn-disabled': 'opacity-70 cursor-not-allowed pointer-events-none',
    'btn-loading': 'cursor-wait',
    'btn-icon': 'aspect-square p-0 inline-flex items-center justify-center',
    'btn-icon-sm': 'w-8 h-8',
    'btn-icon-md': 'w-10 h-10',
    'btn-icon-lg': 'w-12 h-12',
    'btn-focus': 'focus-visible:shadow-focus-primary',
    'btn-spinner': 'absolute flex items-center justify-center inset-0',
    
    // Utility shortcuts pro vaše komponenty
    'btn-large': 'btn-primary px-10 py-4 text-lg',
    'container-custom': 'max-w-1280px mx-auto px-8',
    'section-padding': 'py-24',

    // Layout shortcuts
    'flex-center': 'flex items-center justify-center',
    'flex-between': 'flex items-center justify-between',

    // Typography shortcuts
    'heading-xl': 'text-4xl md:text-5xl lg:text-6xl font-900 leading-tight',
    'heading-lg': 'text-3xl md:text-4xl font-800',
    'body-lg': 'text-lg leading-relaxed',
    
    // Focus states
    'shadow-focus-primary': '0 0 0 3px rgba(230, 0, 0, 0.4)',
    'shadow-focus-secondary': '0 0 0 3px rgba(150, 182, 35, 0.4)',
    
    // Card utilities
    'card': 'rounded-xl overflow-hidden transition-all duration-300 flex flex-col h-full',
    'card-white': 'bg-white shadow-md',
    'card-primary': 'bg-primary/5 border border-primary/20',
    'card-secondary': 'bg-secondary/5 border border-secondary/20',
    'card-light': 'bg-gray-50 border border-gray-100',
    'card-dark': 'bg-gray-800 text-white',
    'card-hover': 'cursor-pointer hover:-translate-y-1.5 hover:shadow-lg',
    'card-bordered': 'border border-gray-200',
    'card-content': 'flex flex-col flex-1 p-6',
    'card-content-tight': 'flex flex-col flex-1 p-4',
    'card-no-padding': 'p-0',
    'card-header': 'mb-4',
    'card-title': 'text-xl font-bold mb-2 leading-tight',
    'card-subtitle': 'text-sm text-gray-600 leading-relaxed',
    'card-body': 'flex-1',
    'card-footer': 'mt-6 pt-4 border-t border-gray-100',
    'card-image': 'relative w-full overflow-hidden',
    'card-img': 'w-full h-auto block transition-transform duration-500 hover:scale-105',
    
    // Modal utilities
    'modal-wrapper': 'fixed inset-0 flex justify-center items-start z-1000 opacity-0 pointer-events-none transition-opacity duration-300',
    'modal-open': 'opacity-100 pointer-events-auto',
    'modal-backdrop': 'absolute inset-0 bg-black/50 backdrop-blur-sm',
    'modal-container': 'relative bg-white rounded-xl shadow-2xl m-8 max-h-[calc(100vh-4rem)] flex flex-col overflow-hidden z-1 w-full',
    'modal-centered': 'my-auto',
    'modal-sm': 'max-w-96',
    'modal-md': 'max-w-128',
    'modal-lg': 'max-w-192',
    'modal-xl': 'max-w-256',
    'modal-full': 'max-w-[90vw] max-h-[90vh]',
    'modal-close': 'absolute top-4 right-4 w-8 h-8 flex items-center justify-center border-0 bg-transparent text-gray-600 rounded-full cursor-pointer transition-all duration-200 z-1 hover:bg-black/5 hover:text-primary',
    'modal-header': 'px-6 pt-6 pb-3 border-b border-gray-100',
    'modal-title': 'text-xl font-bold text-gray-900 leading-relaxed',
    'modal-body': 'p-6 overflow-y-auto flex-1',
    'modal-footer': 'px-6 pb-6 pt-3 flex justify-end gap-3 border-t border-gray-100',
    'modal-fullscreen-mobile': 'sm:m-4 m-0 sm:max-h-[calc(100vh-2rem)] max-h-screen h-screen w-screen sm:w-full sm:rounded-xl rounded-0',
    
    // Badge utilities
    'badge': 'inline-flex items-center justify-center font-semibold leading-none whitespace-nowrap rounded-md',
    'badge-sm': 'text-xs px-1.5 py-0.5',
    'badge-md': 'text-sm px-2.5 py-1',
    'badge-lg': 'text-base px-3.5 py-1.5',
    'badge-rounded': 'rounded-full',
    'badge-outlined': 'bg-transparent border border-current',
    'badge-primary': 'bg-primary text-white',
    'badge-secondary': 'bg-secondary text-white',
    'badge-success': 'bg-green-600 text-white',
    'badge-danger': 'bg-red-600 text-white',
    'badge-warning': 'bg-yellow-500 text-white',
    'badge-info': 'bg-cyan-600 text-white',
    'badge-light': 'bg-gray-100 text-gray-900',
    'badge-dark': 'bg-gray-900 text-white',
    'badge-dot': 'pl-2.5',
    'badge-dot-indicator': 'w-2 h-2 rounded-full inline-block mr-1.5',
    
    // Form Input utilities
    'input-group': 'flex flex-col gap-2',
    'input-label': 'text-sm font-semibold text-gray-300 flex items-center gap-1',
    'input-sublabel': 'font-normal text-gray-400',
    'form-input': 'w-full p-3 bg-gray-800 border border-gray-600 rounded-lg text-white text-sm transition-all duration-200 focus:border-secondary focus:ring-2 focus:ring-secondary/20 focus:outline-none focus:-translate-y-0.5 focus:shadow-lg focus:shadow-secondary/15 placeholder:text-gray-500',
    'form-input-error': 'border-red-500 focus:border-red-500 focus:ring-red-500/20',
    'input-help': 'text-xs text-gray-400 m-0',
    'input-error': 'text-xs text-red-500 m-0',
    
    // HomeHero utilities
    'home-hero': 'relative min-h-[calc(100vh-80px)] flex flex-col justify-center bg-gray-50 overflow-hidden',
    'hero-content-grid': 'grid grid-cols-1 lg:grid-cols-2 gap-12 items-center',
    'hero-text-content': 'flex flex-col items-start lg:items-start items-center text-center lg:text-left',
    'hero-title': 'flex flex-col font-extrabold mb-6 leading-tight',
    'text-gradient': 'text-xl bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent inline-block mb-3',
    'hero-title-main': 'text-4xl md:text-5xl lg:text-6xl text-gray-800',
    'hero-subtitle': 'text-lg lg:text-xl text-gray-600 mb-10 leading-relaxed max-w-128',
    'hero-cta-buttons': 'flex flex-col sm:flex-row gap-4 mb-12 justify-center lg:justify-start w-full sm:w-auto',
    'hero-stats': 'flex flex-col sm:flex-row gap-6 lg:gap-10 items-center lg:items-start',
    'stat-item': 'flex flex-col items-center lg:items-start',
    'stat-value': 'text-3xl lg:text-4xl font-extrabold text-primary',
    'stat-label': 'text-sm text-gray-600',
    'hero-visual-content': 'relative order-first lg:order-last',
    'hero-image-container': 'relative w-full h-full min-h-80 lg:min-h-112',
    'hero-image': 'w-full h-auto max-w-[90%] block mx-auto relative z-1',
    'floating-element': 'absolute z-2',
    'floating-badge-1': 'top-[15%] left-0 lg:left-0 left-[5%]',
    'floating-badge-2': 'top-[40%] lg:top-[40%] top-[30%] right-[10%] lg:right-[10%] right-[5%]',
    'floating-badge-3': 'bottom-[20%] lg:bottom-[20%] bottom-[15%] left-[15%] lg:left-[15%] left-[10%]',
    'visual-element': 'absolute z-3',
    'code-snippet': 'bottom-[10%] right-[5%] bg-gray-800 text-gray-200 p-3 rounded-lg font-mono text-sm shadow-lg transform rotate-3',
    'design-element': 'absolute opacity-5',
    'design-circle-1': 'w-120 h-120 rounded-full bg-primary -top-60 -right-40',
    'design-circle-2': 'w-80 h-80 rounded-full bg-secondary -bottom-40 -left-20',
    'hero-trust-section': 'mt-24 text-center',
    'trust-title': 'text-lg font-semibold text-gray-600 mb-6',
    'trust-logos': 'flex justify-center items-center flex-wrap gap-8 sm:gap-4',
    'logo-placeholder': 'h-8 sm:h-10 w-24 sm:w-32 bg-gray-100 flex items-center justify-center rounded-lg text-gray-400 text-sm',
    'hero-divider': 'relative w-full h-30 mt-auto text-white',
    
    // AppHeader/Navigation utilities
    'vertical-nav': 'flex flex-col gap-4',
    'nav-item': 'block p-3 border border-primary/30 rounded-lg bg-white/5 backdrop-blur-sm transition-all duration-300 hover:border-secondary/50 hover:bg-white/10',
    'nav-link': 'block no-underline transition-all duration-300 cursor-pointer border-0 bg-transparent p-0',
    'nav-text': 'font-bold text-base tracking-wide text-primary transition-colors duration-300 block hover:text-secondary',
    'nav-text-active': 'text-secondary',
    'menu-items': 'flex flex-col gap-4 max-h-0 overflow-hidden opacity-0 transition-all duration-300',
    'menu-items-open': 'max-h-96 opacity-100 mt-4',
    'logo-item': 'cursor-pointer bg-transparent border-0 p-0 transition-transform duration-300 relative hover:scale-105 hover:border-0 hover:bg-transparent',
    'logo-link': 'bg-transparent border-0 p-0 relative',
    'menu-bubble': 'absolute top-1/2 left-full -translate-y-1/2 ml-4 bg-primary text-white px-3 py-2 rounded-full text-xs font-semibold opacity-0 -translate-x-2.5 transition-all duration-400 pointer-events-none whitespace-nowrap z-25',
    'menu-bubble-visible': 'opacity-100 translate-x-0',
    'bubble-arrow': 'absolute -left-1.5 top-1/2 -translate-y-1/2 w-0 h-0 border-t-1.5 border-b-1.5 border-r-1.5 border-transparent border-r-primary',
    'mobile-toggle': 'bg-transparent border-0 cursor-pointer z-21',
    'hamburger': 'w-6 h-4.5 relative cursor-pointer',
    'hamburger-line': 'block w-full h-0.5 bg-primary my-1 transition-all duration-300 rounded-sm',
    'hamburger-active-1': 'bg-secondary transform rotate-45 translate-x-1.25 translate-y-1.25',
    'hamburger-active-2': 'opacity-0',
    'hamburger-active-3': 'bg-secondary transform -rotate-45 translate-x-1.75 -translate-y-1.5',
    'mobile-menu': 'fixed inset-0 bg-white/95 backdrop-blur-lg -translate-x-full opacity-0 transition-all duration-300 pointer-events-none z-20',
    'mobile-menu-open': 'translate-x-0 opacity-100 pointer-events-auto',
    'mobile-menu-content': 'flex flex-col justify-center items-center h-screen gap-8 p-8',
    'mobile-link': 'text-2xl font-bold no-underline text-primary bg-transparent border-0 cursor-pointer transition-colors duration-300 tracking-wide hover:text-secondary',
    'cta-link': 'relative',
    'cta-nav-text': 'font-extrabold text-white relative z-2 drop-shadow-sm',
    'cta-nav-item': 'bg-primary border-2 border-primary shadow-lg shadow-primary/30 scale-102 hover:bg-secondary hover:border-secondary hover:shadow-secondary/40 hover:scale-105',
    
    // CaseStudies utilities
    'case-studies-section': 'relative bg-gray-50',
    'section-header': 'text-center max-w-3xl mx-auto mb-16',
    'section-title': 'text-4xl font-extrabold text-gray-900 mb-4',
    'section-subtitle': 'text-lg text-gray-600 leading-relaxed',
    'case-studies-slider': 'relative',
    'slider-controls': 'flex items-center justify-center mb-8 gap-6',
    'slider-arrow': 'flex items-center justify-center w-12 h-12 rounded-full bg-white border border-gray-200 text-gray-600 cursor-pointer transition-all duration-200 hover:bg-gray-50 hover:text-gray-900 hover:-translate-y-0.5 hover:shadow-md disabled:opacity-50 disabled:cursor-not-allowed',
    'slider-dots': 'flex gap-2',
    'slider-dot': 'w-3 h-3 rounded-full bg-gray-300 border-0 cursor-pointer transition-all duration-200 hover:bg-gray-400',
    'slider-dot-active': 'bg-primary scale-120',
    'slider-container': 'relative w-full overflow-hidden rounded-xl mb-12',
    'slider-track': 'flex transition-transform duration-500 ease-out',
    'case-study-slide': 'min-w-full flex-none',
    'case-study-card': 'grid grid-cols-1 lg:grid-cols-2 bg-white rounded-xl overflow-hidden shadow-xl',
    'case-study-content': 'p-8 lg:p-12 flex flex-col',
    'case-study-header': 'mb-6',
    'case-study-title': 'text-2xl font-bold text-gray-900 mt-4 mb-2',
    'case-study-client': 'text-base text-gray-600',
    'case-study-description': 'text-gray-700 leading-relaxed mb-6',
    'case-study-results': 'mb-8',
    'results-title': 'text-lg font-semibold text-gray-900 mb-4',
    'results-grid': 'grid grid-cols-3 gap-6',
    'result-item': 'text-center',
    'result-value': 'text-2xl font-bold text-primary mb-1',
    'result-label': 'text-sm text-gray-600',
    'case-study-actions': 'mt-auto',
    'case-study-image': 'relative overflow-hidden flex items-center justify-center bg-gray-50',
    'study-image': 'w-full h-full object-cover',
    'case-studies-cta': 'flex flex-col items-center text-center gap-6',
    'cta-text': 'text-lg text-gray-700',
    
    // Responsive variants for CaseStudies
    'case-studies-mobile': 'lg:order-1 order-1',
    'case-studies-image-mobile': 'min-h-75 lg:order-0 order-0',
    'case-studies-content-mobile': 'p-6 lg:p-8',
    'case-study-title-mobile': 'text-xl lg:text-2xl',
    'results-grid-mobile': 'grid-cols-3 gap-4 lg:gap-6',
    'result-value-mobile': 'text-xl lg:text-2xl',
    'result-label-mobile': 'text-xs lg:text-sm',
    'slider-controls-mobile': 'gap-3 lg:gap-6',
    'slider-arrow-mobile': 'w-10 h-10 lg:w-12 lg:h-12',
    
    // ServiceModal utilities
    'service-modal-container': 'fixed inset-0 flex items-center justify-center z-1000 p-4',
    'modal-backdrop-blur': 'absolute inset-0 bg-black/70 backdrop-blur',
    'modal-content-form': 'relative w-full max-w-2xl max-h-[90vh] overflow-y-auto bg-white rounded-xl shadow-2xl p-8',
    'modal-loading': 'opacity-70 pointer-events-none',
    'modal-close-btn': 'absolute top-4 right-4 bg-transparent border-0 text-gray-600 cursor-pointer w-8 h-8 flex items-center justify-center rounded-full transition-all duration-200 hover:bg-black/5 hover:text-primary',
    'modal-header-section': 'mb-8 text-center',
    'modal-title-form': 'text-2xl font-bold mb-2 text-gray-900',
    'modal-subtitle-form': 'text-gray-600 text-sm',
    'modal-form-container': 'flex flex-col gap-5',
    'form-group-modal': 'flex flex-col gap-2',
    'form-label-modal': 'text-sm font-semibold text-gray-700',
    'form-input-modal': 'w-full p-3 border border-gray-300 rounded-lg text-base transition-all duration-200 focus:outline-none focus:border-primary focus:shadow-focus-primary',
    'form-select-modal': 'w-full p-3 border border-gray-300 rounded-lg text-base transition-all duration-200 focus:outline-none focus:border-primary focus:shadow-focus-primary',
    'form-textarea-modal': 'w-full p-3 border border-gray-300 rounded-lg text-base transition-all duration-200 focus:outline-none focus:border-primary focus:shadow-focus-primary resize-vertical',
    'checkbox-group-modal': 'flex items-start',
    'checkbox-container-modal': 'flex relative pl-8 cursor-pointer select-none',
    'checkbox-input-modal': 'absolute opacity-0 cursor-pointer h-0 w-0',
    'checkmark-modal': 'absolute top-0 left-0 h-5 w-5 bg-gray-100 border border-gray-300 rounded',
    'checkmark-checked': 'bg-primary border-primary',
    'checkmark-hover': 'hover:bg-gray-200',
    'checkbox-text-modal': 'text-sm text-gray-700 leading-relaxed',
    'checkbox-link': 'text-primary no-underline hover:underline',
    'form-actions-modal': 'mt-4 flex justify-center',
    'btn-submit-modal': 'inline-flex items-center justify-center px-8 py-3 font-semibold text-white bg-primary border-0 rounded-lg cursor-pointer transition-all duration-300 min-w-48 min-h-12 hover:bg-red-700 hover:-translate-y-0.5 hover:shadow-lg hover:shadow-primary/20 disabled:opacity-70 disabled:cursor-not-allowed',
    'spinner-modal': 'w-5 h-5 mr-2',
    'success-message-modal': 'text-center p-8 flex flex-col items-center',
    'success-icon-modal': 'mb-6',
    'success-title-modal': 'text-2xl font-bold mb-4 text-gray-900',
    'success-text-modal': 'text-gray-600 mb-6 max-w-96',
    'btn-close-success-modal': 'px-8 py-3 font-semibold text-white bg-secondary border-0 rounded-lg cursor-pointer transition-all duration-300 hover:bg-green-700 hover:-translate-y-0.5 hover:shadow-lg hover:shadow-secondary/20',
    
    // PackageCard utilities
    'package-card': 'opacity-0 translate-y-7.5 transition-all duration-800 scroll-mt-25',
    'package-card-visible': 'opacity-100 translate-y-0',
    'package-card-inner': 'bg-gray-50 rounded-2xl p-8 shadow-md border-2 border-transparent transition-all duration-500 relative overflow-hidden hover:shadow-xl hover:border-secondary',
    'package-card-featured': 'border-primary scale-102 shadow-lg',
    'featured-badge-container': 'absolute -top-1 left-1/2 -translate-x-1/2 z-10',
    'featured-badge': 'bg-primary text-white px-6 py-2 rounded-full text-sm font-semibold',
    'package-content-grid': 'grid grid-cols-1 lg:grid-cols-2fr-1fr gap-12',
    'package-header-section': 'mb-8',
    'package-category-badge': 'bg-primary text-white px-4 py-2 rounded-full text-sm font-semibold inline-block mb-4',
    'package-title-card': 'text-3xl font-extrabold mb-4 text-gray-900 transition-colors duration-300 hover:text-secondary',
    'package-title-featured': 'hover:text-primary',
    'package-description-card': 'text-xl text-gray-600 leading-relaxed',
    'package-features-grid': 'grid grid-cols-1 md:grid-cols-2 gap-8',
    'features-section-card': 'space-y-4',
    'features-title-card': 'text-xl font-bold mb-4 text-gray-900',
    'features-list-card': 'list-none p-0 flex flex-col gap-3',
    'feature-item-card': 'flex items-start gap-3',
    'feature-icon-card': 'text-secondary text-lg mt-0.5 flex-shrink-0',
    'feature-icon-featured': 'text-primary',
    'feature-content-card': 'text-sm',
    'feature-description-card': 'text-gray-600',
    'impact-section-card': 'space-y-4',
    'impact-title-card': 'text-xl font-bold mb-4 text-gray-900',
    'impact-metrics-card': 'flex flex-col gap-4 mb-6',
    'impact-metric-card': 'flex items-center gap-3',
    'metric-value-card': 'text-2xl font-extrabold text-secondary',
    'metric-value-featured': 'text-primary',
    'metric-label-card': 'text-gray-600 text-sm',
    'package-meta-card': 'bg-secondary/10 p-4 rounded-xl border-l-4 border-secondary',
    'package-meta-featured': 'bg-primary/10 border-primary',
    'meta-item-card': 'text-sm mb-2 last:mb-0',
    'package-cta-section': 'flex justify-center',
    'price-card-container': 'bg-white p-6 rounded-xl shadow-md border border-gray-200 text-center w-full max-w-70',
    'price-section-card': 'mb-6',
    'price-label-card': 'text-sm text-gray-600 mb-2',
    'price-main-card': 'text-4xl font-extrabold text-primary mb-1',
    'price-average-card': 'text-sm text-gray-600',
    'cta-button-card': 'w-full px-6 py-3 rounded-xl font-semibold text-center transition-all duration-300 border-0 cursor-pointer mb-4',
    'cta-primary-card': 'bg-primary text-white hover:bg-red-700',
    'cta-secondary-card': 'bg-secondary text-white hover:bg-green-700',
    'roi-link-card': 'text-secondary text-sm font-semibold no-underline transition-colors duration-300 hover:underline',
    'roi-link-featured': 'text-primary',
  },
})
